CREATE OR REPLACE FUNCTION GET_AREA
(
	V_DEPTNO		EMP2.DEPTNO%TYPE
) RETURN VARCHAR2
IS
	DAREA		DEPT2.AREA%TYPE;
BEGIN
	SELECT area INTO DAREA
  	  FROM DEPT2 WHERE DCODE = V_DEPTNO;

	RETURN DAREA;
END GET_AREA;
