CREATE OR REPLACE PROCEDURE ENAME_SAL
(
	V_EMPNO		EMP.EMPNO%TYPE
)
IS
	V_ENAME		EMP.ENAME%TYPE;
	V_SAL		EMP.SAL%TYPE;
BEGIN
	SELECT ENAME, SAL INTO V_ENAME, V_SAL
	  FROM EMP
	 WHERE EMPNO = V_EMPNO;

	DBMS_OUTPUT.PUT_LINE('NAME IS' || V_ENAME);
	DBMS_OUTPUT.PUT_LINE('SALARY IS' || V_SAL);
END ENAME_SAL;
