CREATE OR REPLACE FUNCTION GET_DNAME
(
	--V_DEPTNO		DEPT2.DCODE%TYPE
	V_DEPTNO		EMP2.DEPTNO%TYPE
) RETURN VARCHAR2
IS
	DEPTNAME		DEPT2.DNAME%TYPE;
BEGIN
	SELECT DNAME INTO DEPTNAME
  	  FROM DEPT2 WHERE DCODE = V_DEPTNO;
END GET_DNAME;
