CREATE OR REPLACE PROCEDURE INFO_EMP
(
	V_EMPNO		IN  EMP.EMPNO%TYPE,
	O_ENAME		OUT EMP.ENAME%TYPE,
	O_SAL		OUT EMP.SAL%TYPE
)
IS
BEGIN
	SELECT ENAME, SAL INTO O_ENAME, O_SAL
	  FROM EMP
	 WHERE EMPNO = V_EMPNO;

END INFO_EMP;
