CALL UP_SAL(7900);

SELECT * FROM EMP WHERE EMPNO = 7900;

CALL ENAME_SAL(7369);

-- INFO_EMP 프로시저 실행 PL/SQL
DECLARE
	V_EMPNO		EMP.EMPNO%TYPE;
	O_ENAME 	EMP.ENAME%TYPE;
	O_SAL		EMP.SAL%TYPE;
BEGIN
	V_EMPNO := 7900;

	INFO_EMP(V_EMPNO,O_ENAME,O_SAL); -- 저장 프로시저 실행 후 O_ENAME,O_SAL 로 값을 돌려받음
	DBMS_OUTPUT.PUT_LINE(V_EMPNO || '는 이름은' || O_ENAME || '이고, 급여는' || O_SAL);
END;

COMMIT;