-- 특정부서 최고급여 리턴 함수
CREATE OR REPLACE FUNCTION MAX_SAL
(
	V_DEPTNO EMP.DEPTNO%TYPE	
)
RETURN NUMBER
IS
	MAX_SAL	EMP.SAL%TYPE;
BEGIN
	SELECT MAX(SAL) INTO MAX_SAL
	  FROM EMP
	 WHERE DEPTNO = V_DEPTNO;

	RETURN MAX_SAL;
END MAX_SAL;
