-- 커서를 이용해서 모든 EMP 정보를 조회하는 프로시저
CREATE OR REPLACE PROCEDURE EMP_LIST
IS
	CURSOR CUR_EMP IS
		SELECT EMPNO,ENAME,JOB
		  FROM EMP;
BEGIN
	FOR EMP_CNT IN CUR_EMP
	LOOP
		DBMS_OUTPUT.PUT_LINE(EMP_CNT.EMPNO || ',' || EMP_CNT.ENAME || ',' || EMP_CNT.JOB);
	END LOOP;
	
END EMP_LIST;
