-- TRIGGER 연습
-- DEPT 테이블 복사 DEPT_BACK_UP
CREATE TABLE DEPT_BACKUP
AS
	SELECT * FROM DEPT;

-- DEPT_BACKUP 테이블에 LOG_DATA 컬럼 추가
ALTER TABLE DEPT_BACKUP
	ADD(LOG_DATA DATE);

-- TRIGGER 작성
CREATE OR REPLACE TRIGGER TRG_DEPTBACK
AFTER INSERT OR UPDATE OR DELETE ON DEPT -- DEPT 테이블 트리거메뉴에 저장확인
FOR EACH ROW
BEGIN
	IF INSERTING THEN -- DEPT 테이블에 데이터가 추가되면
		INSERT INTO DEPT_BACKUP
		VALUES(:NEW.DEPTNO, :NEW.DNAME, :NEW.LOC, SYSDATE);
	ELSIF UPDATING THEN -- DEPT 테이블에 데이터가 수정되면
	/*	UPDATE DEPT_BACKUP
		   SET DNAME    = :NEW.DNAME,
		       LOC      = :NEW.LOC,
		       LOG_DATE = SYSDATE
		 WHERE DEPTNO = :OLD.DEPTNO; */
		INSERT INTO DEPT_BACKUP
		VALUES(:OLD.DEPTNO, :NEW.DNAME, :NEW.LOC, SYSDATE);
--	ELSIF DELETING THEN
--		DELETE FROM DEPT_BACKUP
--		 WHERE DEPTNO = :OLD.DEPTNO;
	END IF;
END;

-- 원본 확인
SELECT * FROM DEPT;


-- 백업데이터 확인
SELECT * FROM DEPT_BACKUP;

-- 삽입
INSERT INTO DEPT VALUES (50,'R&D','SEOUL');

-- 수정 -> BOSTON에서 LOS ANGELES로
UPDATE DEPT
	SET LOC = 'LOS ANGELES'
 WHERE DEPTNO = 40;