-- EMP 테이블 조회해서 사원번호, 이름, 급여, 부서번호, 인상급여
CREATE OR REPLACE PROCEDURE EMP_INFO
(
	V_EMPNO		EMP.EMPNO%TYPE
)
IS
	O_ENAME		EMP.ENAME%TYPE;
	O_SAL		EMP.SAL%TYPE;
	O_DEPTNO	EMP.DEPTNO%TYPE;
	O_UPSAL		EMP.SAL%TYPE;
BEGIN
	
	SELECT ENAME, SAL, DEPTNO
	  INTO O_ENAME, O_SAL, O_DEPTNO
	  FROM EMP
	 WHERE EMPNO = V_EMPNO;
	
	O_UPSAL := CASE
					WHEN O_DEPTNO = 10 THEN O_SAL * 1.3
					WHEN O_DEPTNO IN(20,30) THEN O_SAL * 1.5
					WHEN O_DEPTNO > 30 THEN O_SAL * 1.2
					ELSE O_SAL
				END;
	DBMS_OUTPUT.PUT_LINE(V_EMPNO || '=>' || O_ENAME || ',' || O_SAL || ',' || O_DEPTNO || ',' || O_UPSAL);
					
END EMP_INFO;
