/*
 * JOIN
 * */
-- 정규화되어 나누어진 테이블의 데이터를 한번에 모아서 쉽게 출력하기 위해 사용하는 기법
SELECT * 
	FROM EMPLOYEES
  WHERE DEPARTMENT_ID = 20;

SELECT *
	FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = 100;

SELECT *
  FROM EMPLOYEES e ,DEPARTMENTS d
  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 카티시안곱
-- 데이터 수가 2,889개
SELECT *
  FROM EMPLOYEES e ,DEPARTMENTS d
 
-- 오라클 방식
SELECT *
  FROM EMPLOYEES e ,DEPARTMENTS d
  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- ANSI 문법
SELECT *
  FROM EMPLOYEES e
  INNER JOIN DEPARTMENTS d
  		  ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID;

-- 필요컬럼만 명세
SELECT E.EMPLOYEE_ID,E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, E.EMAIL, E.PHONE_NUMBER, E.HIRE_DATE, E.JOB_ID, 
	   D.DEPARTMENT_NAME, D.DEPARTMENT_ID,
	   L.CITY, L.STREET_ADDRESS, L.STATE_PROVINCE
  FROM EMPLOYEES e ,DEPARTMENTS d, LOCATIONS l 
  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
	AND L.LOCATION_ID  = D.LOCATION_ID
	AND D.DEPARTMENT_ID = 60;

-- 내부조인(INNER JOIN)
SELECT E.EMPLOYEE_ID,E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME, E.EMAIL, E.PHONE_NUMBER, E.HIRE_DATE, E.JOB_ID, 
	   D.DEPARTMENT_NAME, D.DEPARTMENT_ID,
	   L.CITY, L.STREET_ADDRESS, L.STATE_PROVINCE
  FROM EMPLOYEES e ,DEPARTMENTS d, LOCATIONS l 
  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
	AND L.LOCATION_ID  = D.LOCATION_ID
	AND D.DEPARTMENT_ID = 60;





