/*
 * DDL - 데이터조작언어
 * CREATE, ALTER, DROP, TRUNCATE
 * 객체를 생성, 수정, 삭제, 데이터를 초기화
 * */

-- NO,NAME,BIRTH 컬럼의 테이블 NEW_TABLE을 생성
CREATE TABLE new_table(
	NO    NUMBER(5,0) PRIMARY KEY,
	JUMIN CHAR(14),
	NAME  VARCHAR2(20) NOT NULL,
	BIRTH DATE
);

-- 삭제
DROP TABLE new_table;


-- 기본값을 설정하면서 TABLE을 생성
CREATE TABLE new_table(
	NO    NUMBER(5,0) PRIMARY KEY,
	NAME  VARCHAR2(20) NOT NULL,
	JUMIN CHAR(14),	
	BIRTH DATE,
	SALARY NUMBER(7,0) DEFAULT 0 -- 아무값도 넣지 않고 INSERT 하면 NULL 을 0 으로 대체
);

-- 테이블 컬럼에 주석 추가
COMMENT ON COLUMN new_table.name IS '사원이름';

-- 기본키가 2개인 테이블 생성
CREATE TABLE DOUBLEKEYTB(
	ID NUMBER(5,0),
	CODE CHAR(4),
	NAME VARCHAR2(20) NOT NULL,
	JUMIN CHAR(14) UNIQUE,
	CONSTRAINT PK_DK PRIMARY KEY(ID, CODE)
);


-- NEW_MEMBER 부모테이블과 NEW_BOARD 자식테이블 간의 관계가 성립된 테이블을 생성하시오
CREATE TABLE NEW_MEMBER(
	IDX  NUMBER(5,0)   PRIMARY KEY,
	NAME VARCHAR2(20)  NOT NULL,
	ID   VARCHAR2(20)  NOT NULL,
	PWD  VARCHAR2(256) NOT NULL
);

-- NEW_BOARD 는 NEW_MEMBER 의 PK IDX 를 외래키로 사용
CREATE TABLE NEW_BOARD(
	BIDX      NUMBER(5,0)   PRIMARY KEY,
	TITLE     VARCHAR2(20)  NOT NULL,
	CONTENT   LONG          NOT NULL,
	REG_DATE  DATE          DEFAULT SYSDATE,
	COUNT     NUMBER(6,0)   DEFAULT 0,
	MIDX      NUMBER        NOT NULL,
	CONSTRAINT FK_MEMBERIDX FOREIGN KEY(MIDX) REFERENCES NEW_MEMBER(IDX)
);

-- ALTER 기존 테이블을 수정할 때 사용
ALTER TABLE NEW_TABLE ADD (ADDRESS VARCHAR2(200));

-- ALTER 기존 테이블에 전화번호 칼럼 추가
-- 데이터가 이미 존재하는 테이블에 NOT NULL 칼럼은 추가 불가
-- ALTER TABLE NEW_TABLE ADD(TEL VARCHAR2(20) NOT NULL); - 불가
ALTER TABLE NEW_TABLE ADD(TEL VARCHAR2(20));

-- 칼럼 수정 VARCHAR2(200) -> VARCHAR2(100)
ALTER TABLE NEW_TABLE MODIFY (ADDRESS VARCHAR2(100));

-- DROP 테이블
DROP TABLE NEW_TABLE PURGE;

-- TRUNCATE 테이블 초기화
-- ID 값이 자동으로 증가하는 것을 지움
TRUNCATE TABLE NEW_TABLE;
