-- 1. 연봉이 12000 이상되는 직원들의 LAST_NAME 및 연봉을 조회
SELECT E.LAST_NAME,
	   e.SALARY 
  FROM EMPLOYEES e 
 WHERE SALARY >= 12000;

-- 2. 사원번호가 176 인 사람의 LAST_NAME 과 부서 번호를 조회
SELECT * FROM EMPLOYEES e 


SELECT E.LAST_NAME,
	   e.DEPARTMENT_ID 
  FROM EMPLOYEES e
 WHERE e.EMPLOYEE_ID = 176;


-- 3. 연봉이 5000 에서 12000의 범위 이외인 사람들의 LAST_NAME 및 연봉을 조회
SELECT E.LAST_NAME,
	   e.SALARY 
  FROM EMPLOYEES e 
 WHERE SALARY NOT BETWEEN 5000 AND 12000;

